<?php
define('titre', 'Gestión de productos');
define('stitre', 'Añade, elimina, busca tus productos aquí');
define('ajout', 'añadir producto');
define('codeprod', 'código de producto');
define('des', 'designación');
define('prix', 'precio de compra');
define('mar', 'margen');
define('qua', 'cantidad');
define('seu', 'umbral');
define('fou', 'proveedor');
define('img', 'imagen');
define('val', 'validar');
define('ini', 'inicializar');
define('RECHERCHE_TITRE', 'Buscar por cualquier información');
define('LABEL_CODE_PROD', 'Ingrese el código del producto:');
define('BTN_SUBMIT', 'Aceptar');
define('TABLE_ID', 'ID');
define('TABLE_CODE_PROD', 'Código Prod');
define('TABLE_DESIGNATION', 'Designación');
define('TABLE_PRIX_A', 'Precio A');
define('TABLE_MARGE', 'Margen');
define('TABLE_QUANTITE_STOCK', 'Cantidad en Stock');
define('TABLE_SEUIL', 'Umbral');
define('TABLE_ID_FOURNISSEUR', 'Proveedor');
define('TABLE_TITLE', 'Tabla de productos');
define('ID', 'ID');
define('CODE_PROD', 'Código de producto');
define('DESIGNATION', 'Designación');
define('PRIX_A', 'Precio A');
define('MARGE', 'Margen');
define('QUANTITE_STOCK', 'Cantidad en Stock');
define('SEUIL', 'Umbral');
define('ID_FOURNISSEUR', 'Proveedor');
define('IMAGE', 'Imagen');
define('NO_RESULT', "No se encontraron resultados para el código de producto.");
define('MODIFIER_DONNEES', 'Modificar datos de producto');
define('NOUVELLE_DESIGNATION', 'Nueva designación');
define('NOUVEAU_PRIX', 'Nuevo precio');
define('NOUVELLE_MARGE', 'Nuevo margen');
define('NOUVELLE_QUANTITE', 'Nueva cantidad');
define('NOUVEAU_SEUIL', 'Nuevo umbral');
define('NOUVEAU_FOURNISSEUR', 'Nuevo proveedor');
define('MODIFIER', 'Modificar');
define('ACTION', 'comportamiento');
define('SUPPRIMER', 'Eliminar');
define('DETAILS', 'Detalles');
define('quitter', 'Salir');

?>
