<?php
define('titre', 'Gestion des produits');
define('stitre', 'Ajoutez, supprimez, recherchez vos produits ici');

define('ajout', 'ajout de produit');
define('codeprod', 'code produit');
define('des', 'designation');
define('prix', 'prix d\'achat');
define('mar', 'marge');
define('qua', 'quantité');
define('seu', 'seuil');
define('fou', 'fournisseur');
define('img', 'image');
define('val', 'valider');
define('ini', 'initialiser');
define('RECHERCHE_TITRE', 'Rechercher par n\'importe quelle information');
define('LABEL_CODE_PROD', 'Entrez le code produit :');
define('BTN_SUBMIT', 'Valider');
define('TABLE_ID', 'ID');
define('TABLE_CODE_PROD', 'Code Prod');
define('TABLE_DESIGNATION', 'Désignation');
define('TABLE_PRIX_A', 'Prix A');
define('TABLE_MARGE', 'Marge');
define('TABLE_QUANTITE_STOCK', 'Quantité Stock');
define('TABLE_SEUIL', 'Seuil');
define('TABLE_ID_FOURNISSEUR', 'Fournisseur');
define('TABLE_TITLE', 'Tableau des produits');
define('ID', 'ID');
define('CODE_PROD', 'Code Prod');
define('DESIGNATION', 'Désignation');
define('PRIX_A', 'Prix A');
define('MARGE', 'Marge');
define('QUANTITE_STOCK', 'Quantité Stock');
define('SEUIL', 'Seuil');
define('ID_FOURNISSEUR', 'Fournisseur');
define('IMAGE', 'Image');
define('NO_RESULT', "Aucun résultat trouvé pour le code produit .");
define('MODIFIER_DONNEES', 'Modifier les données d\'un produit');
define('NOUVELLE_DESIGNATION', 'Nouvelle désignation');
define('NOUVEAU_PRIX', 'Nouveau prix');
define('NOUVELLE_MARGE', 'Nouvelle marge');
define('NOUVELLE_QUANTITE', 'Nouvelle quantité');
define('NOUVEAU_SEUIL', 'Nouveau seuil');
define('NOUVEAU_FOURNISSEUR', 'Nouveau fournisseur');
define('MODIFIER', 'Modifier');
define('ACTION', 'actions');
define('SUPPRIMER', 'Supprimer');
define('DETAILS', 'Détails');
define('quitter', 'Quitter');
?>