<html>
  <head> </head>
  <body>
  <img style="position: absolute; top: 20%; left: 20px;" width="5%" src="img/stock.PNG">
  <img style="position: absolute; top: 20%; left: 70px;" width="60%" src="img/image.svg">
  <?php 
    echo '<a href="main.php?lg=Fr" target="_parent" style="position: absolute; top: 30%; right: 0;"><img src="img/Fr.png" width="30"></a>';
    echo '<a href="main.php?lg=Mr" target="_parent" style="position: absolute; top: 30%; right: 40px;"><img src="img/Mar.png" width="30"></a>';
    echo '<a href="main.php?lg=Ang" target="_parent" style="position: absolute; top: 30%; right: 80px;"><img src="img/Ang.png" width="30"></a>';
    echo '<a href="main.php?lg=Esp" target="_parent" style="position: absolute; top: 30%; right: 120px;"><img src="img/Esp.png" width="30"></a>';
  ?>
  </body>
</html>